In [20]:
import numpy as np
income = np.array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000], dtype = int)
income

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000])

In [30]:
income_without_tax = income * 0.7
income_without_tax

array([ 700., 1400., 2100., 2800., 3500., 4200., 4900., 5600., 6300.,
       7000.])

In [31]:
expenses = np.array([500, 1000, 1000, 2000, 2000, 3000, 3000, 4000, 3000, 2000], dtype = int)
expenses

array([ 500, 1000, 1000, 2000, 2000, 3000, 3000, 4000, 3000, 2000])

In [39]:
import pandas as pd
d = {
    "Expenses (mln. $)": pd.Series(expenses, ["Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct."]),
    "Income without tax (mln. $)": pd.Series(income_without_tax, ["Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct."])
}
annual_report = pd.DataFrame(d)
annual_report

Expenses (mln. $)  Income without tax (mln. $)
Jan.                500                        700.0
Feb.               1000                       1400.0
Mar.               1000                       2100.0
Apr.               2000                       2800.0
May                2000                       3500.0
Jun.               3000                       4200.0
Jul.               3000                       4900.0
Aug.               4000                       5600.0
Sep.               3000                       6300.0
Oct.               2000                       7000.0

In [42]:
annual_report.iloc[:3]

Expenses (mln. $)  Income without tax (mln. $)
Jan.                500                        700.0
Feb.               1000                       1400.0
Mar.               1000                       2100.0